
export const ROOT_CLASS = "__READ_FOR_ME__";

export const STORAGE_OPENAI_API = "__SOTRAGE_OPENAI_API__";
export const STORAGE_SUMMARY_PROMPT = "__SOTRAGE_SUMMARY_PROMPT__";
export const STORAGE_ANSWER_PROMPT = "__SOTRAGE_ANSWER_PROMPT__";
export const STORAGE_SETTING= "__STORAGE_SETTING__";
export const STORAGE_QUESTIONS = "__STORAGE_QUESTIONS__"

export const ACTION_TOGGER_DRAWER= "__TOGGER_DRAWER__";
export const ACTION_SUMMARY_CONTENT = "__ACTION_SUMMARY_CONTENT__"
export const ACTION_ANSWER_CONTENT = "__ACTION_ANSWER_CONTENT__"
export const ACTION_CREATE_RECORD = '__ACTION_CREATE_RECORD__'

export const EVENT_RESPONSE_MSG = "__EVENT_RESPONSE_MSG__"

