name: publish
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'release') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ^8.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Configure Git User
        run: |
          git config --global user.email "2037630@163.com"
          git config --global user.name "zhuchentong"

      - name: Tag Patch Version
        run: npx bumpp patch -y
        if: ${{ startsWith(github.event.head_commit.message, 'release(patch):') }}

      - name: Tag Minor Version
        run: npx bumpp patch -y
        if: ${{ startsWith(github.event.head_commit.message, 'release(minor):') }}

      - name: Tag Major Version
        run: npx bumpp major -y
        if: ${{ startsWith(github.event.head_commit.message, 'release(major):') }}